# Generated by Django 3.2.8 on 2023-06-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('buyer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'buyers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('footer', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('price_per_meter', models.IntegerField(blank=True, null=True)),
                ('number_of_rooms', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('floor', models.CharField(blank=True, max_length=255, null=True)),
                ('rent', models.IntegerField(blank=True, null=True)),
                ('remote_service', models.BooleanField(blank=True, null=True)),
                ('form_of_ownership', models.CharField(blank=True, max_length=255, null=True)),
                ('finishing_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('balcony_garden_terrace', models.CharField(blank=True, max_length=255, null=True)),
                ('parking_space', models.CharField(blank=True, max_length=255, null=True)),
                ('heating', models.CharField(blank=True, max_length=255, null=True)),
                ('market', models.CharField(blank=True, max_length=255, null=True)),
                ('advertiser_type', models.CharField(blank=True, max_length=255, null=True)),
                ('available_from', models.CharField(blank=True, max_length=255, null=True)),
                ('year_of_construction', models.IntegerField(blank=True, null=True)),
                ('type_of_construction', models.CharField(blank=True, max_length=255, null=True)),
                ('windows', models.CharField(blank=True, max_length=255, null=True)),
                ('elevator', models.BooleanField(blank=True, null=True)),
                ('media', models.CharField(blank=True, max_length=255, null=True)),
                ('security', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_infromation', models.CharField(blank=True, max_length=255, null=True)),
                ('building_material', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'offers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sellers',
                'managed': False,
            },
        ),
    ]
