version: '3'
services:
  db:
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - scrap-masters

volumes:
  dbdata:


networks:
  scrap-masters:
    driver: bridge
