version: '3'
services:
  db:
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - scrap-masters
  redis:
    build:
      context: ./redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - scrap-masters

volumes:
  dbdata:
  redisdata:


networks:
  scrap-masters:
    driver: bridge
