"""aaa

Revision ID: 3de8a08eb968
Revises: 77c29471d618
Create Date: 2023-06-10 13:02:16.299595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de8a08eb968'
down_revision = '77c29471d618'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
