"""ccc

Revision ID: 70d19a851112
Revises: 716defcc4e3c
Create Date: 2023-06-10 13:07:50.645644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d19a851112'
down_revision = '716defcc4e3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
