"""bbb

Revision ID: 716defcc4e3c
Revises: 3de8a08eb968
Create Date: 2023-06-10 13:03:18.261327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716defcc4e3c'
down_revision = '3de8a08eb968'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
